sudo: false

language: groovy

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

branches:
  only:
    - master
  
after_success:
  - ./gradlew jacocoTestReport
  - ./gradlew coveralls

notifications:
  email:
    - mr.paul.woods@gmail.com
